kind: Service
apiVersion: v1
metadata:
  name: hello-node-service
spec:
  selector:
    app: hello-node
  type: NodePort  
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30001